# Generated by Django 2.1.7 on 2019-07-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Image',
            new_name='Photo',
        ),
        migrations.AlterField(
            model_name='design',
            name='Description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
